######################################################################
# Automatically generated by qmake (2.01a) Sun Nov 24 14:45:34 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += rss_grabber.hpp rss_gui.hpp rss_item.hpp rss_parser.hpp fragment.hpp
SOURCES += main.cpp rss_grabber.cpp rss_gui.cpp rss_item.cpp rss_parser.cpp fragment.cpp
LIBS += -lcurl
QMAKE_CXXFLAGS += -std=c++11
